### ISSUE TITLE
issue fixed. 

### ISSUE THREAD

**Issue by ranganayakulu** [Joseph-N/chatty#11]
how can i delete this comment?

**Comment by Ranjana1-devi** [comment]
When user A sends messages user B, it is not updating the message in chat box and giving this error.
But on reload page messages are displaying 

Error:
ActionView::Template::Error (Net::ReadTimeout):
    1: http = Net::HTTP.new(@host, @port)
    2: http.read_timeout = 500
    3: <% publish_to @path do %>
    4:     var id = "<%= @conversation.id %>";
    5:     var chatbox = $("#chatbox_" + id + " .chatboxcontent");
    6:     var sender_id = "<%= @message.user.id %>";
_app_views_messages_create_js_erb___797621413192950375_99761160'
